name: crontab

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * 1,3,5'

env:
  DOCKER_IMAGE_NAME: "repasscloud/optechx.portal"

jobs:
  cron-local-build:
    runs-on: ubuntu-latest
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v3

      - name: 🔐 Decrypt Repo
        run: ./decrypt_repo.sh
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PHRASE }}
        shell: bash

      - name: 🐳🏗️ Docker .local Build
        run: docker build --rm --no-cache --tag $DOCKER_IMAGE_NAME:$(date +%s) --file Dockerfile.local .
